dubbo:
  application:
    name: srevice-goods
  registry:
    address: zookeeper://www.img.com:2181
  protocol:
    port: -1
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql:///shop1909?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: www.img.com
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672
mybatis-plus:
  mapper-locations: classpath:com/qf/dao/*.xml
