server:
  port: 8888
spring:
  thymeleaf:
    cache: false
dubbo:
  consumer:
    check: false
  application:
    name: web-goods
  registry:
    address: zookeeper://192.168.50.129:2181
fdfs:
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 192.168.50.129:22122