dubbo:
  application:
    name: service-user
  registry:
    address: zookeeper://www.img.com:2181
  consumer:
    check: false
  protocol:
    port: -1
spring:
  datasource:
    url: jdbc:mysql:///shop1909?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver