spring:
  mail:
    host: smtp.163.com
    protocol: smtp
    username: b657695528@163.com
    password: lin27951035
  rabbitmq:
    host: 192.168.50.129
    username: admin
    password: admin
    virtual-host: /admin
