dubbo:
  application:
    name: service-search
  registry:
    address: zookeeper://www.img.com:2181
  consumer:
    check: false
  protocol:
    port: -1
spring:
  data:
    solr:
      host: http://www.img.com:8983/solr/mycollection

  rabbitmq:
    host: www.img.com
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672

