server:
  port: 8890
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: www.img.com
    username: admin
    password: admin
    virtual-host: /admin
  redis:
    host: www.img.com
dubbo:
  application:
    name: web-sso
  registry:
    address: zookeeper://www.img.com:2181
  consumer:
    check: false
    timeout: 10000
    retries: 0
